# Copyright 2026 Mattia Giambirtone & All Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Authored with assistance from AI agents.

## Multilayer TI inference against an independent canonical-layout oracle.
## Generate EVALFILE with tests/make_multilayer_fixture.py, then build using
## make dev MAIN=tests/test_multilayer.nim IS_TEST=1.
include heimdall/eval
import std/[os, tempfiles, random]

static:
    doAssert not SINGLE_LAYER
    doAssert NUM_INPUT_BUCKETS == 16 and NUM_OUTPUT_BUCKETS == 8
    doAssert L2_SIZE == 16 and L3_SIZE == 32
    doAssert QA == 255 and QUANT_BITS == 6 and FT_SCALE_BITS == 7 and L1_QUANT_BITS == 7

# Keep this oracle independent of the loader's packed layout and SIMD helpers.
# These formulas define the canonical weights generated by the Python fixture.
func firstWeight(input, bucket, output: int): int64 =
    ((input * 11 + bucket * 3 + output * 5) mod 15 - 7).int64

func arithmeticShift(value: int64, bits: int): int64 =
    let divisor = 1'i64 shl bits
    if value >= 0: value div divisor
    else: -((-value + divisor - 1) div divisor)

proc oracle(state: EvalState, stm: PieceColor, bucket: int): int32 =
    const q = 1 shl QUANT_BITS
    var activated: array[L1_SIZE, int64]
    for half, side in [stm, stm.opposite()]:
        for i in 0..<L1_SIZE div 2:
            let j = i + L1_SIZE div 2
            let a = clamp(state.accumulators[side][state.current].data[i].int64 +
                          state.threatAccumulators[side][state.current].data[i].int64, 0, QA)
            let b = clamp(state.accumulators[side][state.current].data[j].int64 +
                          state.threatAccumulators[side][state.current].data[j].int64, 0, QA)
            activated[half * (L1_SIZE div 2) + i] = a * b div (1 shl (16 - FT_SCALE_BITS))
    var hidden: array[L2_SIZE * (1 + DUAL_ACTIVATION.int), int64]
    for o in 0..<L2_SIZE:
        var value = ((o - 7) * 127 + bucket * 31).int64 shl L1_BIAS_SHIFT
        for i in 0..<L1_SIZE:
            value += activated[i] * firstWeight(i, bucket, o)
        value = arithmeticShift(value, 8)
        when DUAL_ACTIVATION:
            hidden[o] = clamp(value, 0, q) * q
            hidden[o + L2_SIZE] = min(value * value, q * q)
        else:
            hidden[o] = clamp(value, 0, q) * clamp(value, 0, q)
    var total = ((bucket - 3) * 12345).int64
    for o in 0..<L3_SIZE:
        var value = ((o - 15) * 97 + bucket * 211).int64
        for i in 0..<hidden.len:
            value += hidden[i] * ((i * 3 + bucket * 7 + o * 11) mod 33 - 16).int64
        total += clamp(value, 0, q * q * q) * ((o * 7 + bucket * 11) mod 129 - 64).int64
    return (total * EVAL_SCALE div (q.int64 * q * q * q)).int32

var owner = newEvalState(verbose=false)
let state = owner.raw

# Spot-check each on-disk region, including signed TI rows and both bucket axes.
for f in [0, 767, FT_SIZE * NUM_INPUT_BUCKETS - 1]:
    for n in [0, L1_SIZE div 2, L1_SIZE - 1]:
        doAssert network.ft.weight[f][n] == ((f * 3 + n * 5) mod 7 - 3).int16
for f in [0, 506, TOTAL_THREATS - 1]:
    for n in [0, L1_SIZE div 2, L1_SIZE - 1]:
        doAssert network.threatWeights[f][n] == ((f * 3 + n * 7) mod 5 - 2).int8
for n in 0..<L1_SIZE:
    doAssert network.ft.bias[n] == (80 + n mod 101).int16
for b in 0..<NUM_OUTPUT_BUCKETS:
    for o in 0..<L2_SIZE:
        doAssert network.l1.bias[b][o] == (((o - 7) * 127 + b * 31).int32 shl L1_BIAS_SHIFT)
    doAssert network.l3.buckets[b].bias[0] == ((b - 3) * 12345).int32

var rng = initRand(0x7A11)
var comparisons, tiChanges: int
for sample in 0..<64:
    for side in White..Black:
        for n in 0..<L1_SIZE:
            state.accumulators[side][0].data[n] = (rng.rand(1023) - 256).int16
            state.threatAccumulators[side][0].data[n] = (rng.rand(767) - 384).int16
    for side in White..Black:
        for bucket in 0..<NUM_OUTPUT_BUCKETS:
            let expected = oracle(state, side, bucket)
            doAssert state.forwardScalar(side, bucket) == expected,
                "scalar/oracle mismatch at sample " & $sample & " bucket " & $bucket
            when defined(simd):
                doAssert state.forwardFast(side, bucket) == expected,
                    "SIMD/oracle mismatch at sample " & $sample & " bucket " & $bucket
            inc(comparisons)
    let withTI = state.forwardScalar(White, sample mod NUM_OUTPUT_BUCKETS)
    for side in White..Black:
        for value in state.threatAccumulators[side][0].data.mitems:
            value = 0
    if state.forwardScalar(White, sample mod NUM_OUTPUT_BUCKETS) != withTI:
        inc(tiChanges)
doAssert tiChanges > 0, "fixture failed to exercise TI's effect on the score"

block largeOutputScaling:
    # A valid int32 final sum can overflow during scaling, even though the
    # dequantized score fits. Exercise both signs and inference backends.
    static: doAssert EVAL_SCALE == 400
    let saved = network.l3.buckets[0]
    defer: network.l3.buckets[0] = saved
    for weight in network.l3.buckets[0].weight.mitems:
        weight[0] = 0
    # 41944 crosses the first score boundary; dividing by Q before scaling
    # would incorrectly discard it. 41943 must still truncate to zero.
    for (bias, expected) in [(41943'i32, 0'i32), (41944'i32, 1'i32),
                             (1_000_000_000'i32, 23841'i32)]:
        for sign in [-1'i32, 1'i32]:
            network.l3.buckets[0].bias[0] = sign * bias
            doAssert state.forwardScalar(White, 0) == sign * expected
            when defined(simd):
                doAssert state.forwardFast(White, 0) == sign * expected

block roundTrip:
    let (file, path) = createTempFile("heimdall-multilayer-", ".bin")
    file.close()
    defer: removeFile(path)
    network.dumpNet(path)
    doAssert readFile(path) == readFile(DEFAULT_NET_PATH), "multilayer disk layout did not round-trip"
    var restored = allocHugePage[Network](zero=true)
    restored.raw[] = loadNet(path)
    doAssert restored.raw.ft == network.ft
    doAssert restored.raw.threatWeights == network.threatWeights
    doAssert restored.raw.l1 == network.l1
    doAssert restored.raw.l2 == network.l2
    doAssert restored.raw.l3 == network.l3

when defined(simd):
    echo "Multilayer backend: SIMD and scalar"
else:
    echo "Multilayer backend: scalar"
echo "Multilayer TI: ", comparisons, " oracle comparisons at width ", L1_SIZE, "; loader/export passed"

printSimdInfo()
